// Auto-generated by: pnpm dlx supabase@latest gen types typescript --project-id <id>
// Run after Supabase project and migrations are set up.
// This is a placeholder so TypeScript compiles before types are generated.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          slug: string;
          vertical: string;
          country: string;
          default_language: string;
          default_currency: string;
          logo_url: string | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          vertical: string;
          country?: string;
          default_language?: string;
          default_currency?: string;
          logo_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["businesses"]["Insert"]>;
      };
      branches: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          slug: string;
          address: string | null;
          city: string | null;
          country: string;
          phone: string | null;
          whatsapp_number: string | null;
          timezone: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          slug: string;
          address?: string | null;
          city?: string | null;
          country?: string;
          phone?: string | null;
          whatsapp_number?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["branches"]["Insert"]>;
      };
      users: {
        Row: {
          id: string;
          business_id: string | null;
          email: string;
          phone: string | null;
          full_name: string | null;
          avatar_url: string | null;
          role: string;
          provider: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          business_id?: string | null;
          email: string;
          phone?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          role: string;
          provider?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
      };
      staff: {
        Row: {
          id: string;
          business_id: string;
          user_id: string | null;
          display_name: string;
          slug: string;
          avatar_url: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id?: string | null;
          display_name: string;
          slug: string;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["staff"]["Insert"]>;
      };
      staff_branches: {
        Row: { id: string; staff_id: string; branch_id: string };
        Insert: { id?: string; staff_id: string; branch_id: string };
        Update: Partial<Database["public"]["Tables"]["staff_branches"]["Insert"]>;
      };
      services: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          duration_minutes: number;
          price: number;
          currency: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          duration_minutes: number;
          price: number;
          currency?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["services"]["Insert"]>;
      };
      branch_services: {
        Row: { id: string; branch_id: string; service_id: string; price_override: number | null };
        Insert: { id?: string; branch_id: string; service_id: string; price_override?: number | null };
        Update: Partial<Database["public"]["Tables"]["branch_services"]["Insert"]>;
      };
      staff_availability: {
        Row: {
          id: string;
          staff_id: string;
          branch_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          branch_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
        };
        Update: Partial<Database["public"]["Tables"]["staff_availability"]["Insert"]>;
      };
      clients: {
        Row: {
          id: string;
          business_id: string;
          full_name: string;
          email: string | null;
          phone: string | null;
          whatsapp_number: string | null;
          preferred_language: string | null;
          total_visits: number;
          total_spent: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          whatsapp_number?: string | null;
          preferred_language?: string | null;
          total_visits?: number;
          total_spent?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
      };
      appointments: {
        Row: {
          id: string;
          business_id: string;
          branch_id: string;
          client_id: string;
          staff_id: string;
          service_id: string;
          starts_at: string;
          ends_at: string;
          status: string;
          notes: string | null;
          created_at: string;
          cancelled_at: string | null;
        };
        Insert: {
          id?: string;
          business_id: string;
          branch_id: string;
          client_id: string;
          staff_id: string;
          service_id: string;
          starts_at: string;
          ends_at: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          cancelled_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["appointments"]["Insert"]>;
      };
      messages: {
        Row: {
          id: string;
          appointment_id: string | null;
          business_id: string;
          type: string;
          channel: string;
          status: string;
          provider_message_id: string | null;
          scheduled_at: string | null;
          sent_at: string | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          appointment_id?: string | null;
          business_id: string;
          type: string;
          channel: string;
          status?: string;
          provider_message_id?: string | null;
          scheduled_at?: string | null;
          sent_at?: string | null;
          error?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["messages"]["Insert"]>;
      };
      message_templates: {
        Row: {
          id: string;
          type: string;
          channel: string;
          language: string;
          vertical: string;
          content: string;
          variables: Json;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          type: string;
          channel: string;
          language: string;
          vertical: string;
          content: string;
          variables?: Json;
          is_active?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["message_templates"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
